# https://dependabot.com/docs/config-file/
version: 1
update_configs:
  - package_manager: "terraform"
    directory: "/live/prod"
    update_schedule: "daily"
  - package_manager: "terraform"
    directory: "/live/dev"
    update_schedule: "daily"
